'use client';

import { useState } from 'react';
import { Sparkles } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { SKILL_TAXONOMY } from '@/lib/types';

/**
 * Parent tool: generate original AI-written questions for a sub-skill.
 * Useful for sub-skills with thin coverage in the uploaded bank.
 */
export function QuestionGenerator() {
  const [skill, setSkill] = useState<string>(SKILL_TAXONOMY.reading_writing[0].id);
  const [count, setCount] = useState('5');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setBusy(true);
    setMessage(null);
    setError(null);
    try {
      const res = await fetch('/api/parent/generate-questions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ sub_skill_id: skill, count: Number(count) }),
      });
      const data = await res.json();
      if (!res.ok) {
        setError(data.error ?? 'Generation failed. Please try again.');
      } else {
        setMessage(
          `Added ${data.generated} AI-generated question${data.generated !== 1 ? 's' : ''} to ${skill}. They're marked with an AI badge in the bank and in sessions.`
        );
      }
    } catch {
      setError('Network error. Please try again.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-base">
          <Sparkles className="h-4 w-4 text-amber-500" />
          Generate Questions with AI
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <p className="text-sm text-gray-500">
          Write original SAT-style questions for a sub-skill with thin coverage.
          Questions are generated by Claude, marked as AI-generated, and join the
          adaptive rotation immediately.
        </p>
        <div className="flex flex-wrap items-end gap-3">
          <div className="min-w-56 space-y-1">
            <label htmlFor="gen-skill" className="text-xs font-medium text-gray-600">
              Sub-skill
            </label>
            <Select value={skill} onValueChange={setSkill}>
              <SelectTrigger id="gen-skill">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <div className="px-2 py-1 text-xs font-semibold text-gray-500">
                  Reading & Writing
                </div>
                {SKILL_TAXONOMY.reading_writing.map((s) => (
                  <SelectItem key={s.id} value={s.id}>
                    {s.id}: {s.name}
                  </SelectItem>
                ))}
                <div className="px-2 py-1 text-xs font-semibold text-gray-500">Math</div>
                {SKILL_TAXONOMY.math.map((s) => (
                  <SelectItem key={s.id} value={s.id}>
                    {s.id}: {s.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1">
            <label htmlFor="gen-count" className="text-xs font-medium text-gray-600">
              How many
            </label>
            <Select value={count} onValueChange={setCount}>
              <SelectTrigger id="gen-count" className="w-20">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {['3', '5', '8', '10'].map((n) => (
                  <SelectItem key={n} value={n}>
                    {n}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <Button onClick={generate} disabled={busy}>
            {busy ? 'Generating (30-60s)...' : 'Generate'}
          </Button>
        </div>
        {message && (
          <p className="rounded-lg bg-green-50 p-2 text-sm text-green-700">{message}</p>
        )}
        {error && (
          <p className="rounded-lg bg-red-50 p-2 text-sm text-red-700" role="alert">
            {error}
          </p>
        )}
      </CardContent>
    </Card>
  );
}
